config/routes.rb
EsShopPractice::Application.routes.draw do

  devise_for :users

  resources :stores

  resources :laptops

  resources :televisions

  resources :cameras

  resources :reviews

  resources :products

  root to: "products#index"

end

app/models/store.rb
class Store

  include Tire::Model::Search
  include Tire::Model::Callbacks
  include MongoMapper::Document
  include Geocoder::Model::MongoMapper

  key :address, String
  key :lon_lat,  Array

  geocoded_by       :address, :coordinates => :lon_lat
  after_validation  :geocode  # auto-fetch coordinates

  mapping do
    indexes :address, type: 'string'
    indexes :lon_lat, type: 'geo_point'
  end

  timestamps!

  def self.s(params, options={})

    # set the query
    q = params[:q] || "London"
    center_lon_lat = Geocoder.search(q).first.coordinates.reverse rescue [0, 0]

    # perform search
    tire.search load: true do |s|
      s.query { all }
      s.sort do
        by :_geo_distance, {
          lon_lat: center_lon_lat ,
          order: "asc",
          unit: 'mi'
        }
      end
    end

  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    search  = Store.s params, load: true
    @stores = search.results

    @map_hash = Gmaps4rails.build_markers(@stores) do |store, marker|
      marker.lat store.lon_lat.last
      marker.lng store.lon_lat.first
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
= form_for @store do |f|
  - if @store.errors.any?
    #error_explanation
      %h2= "#{pluralize(@store.errors.count, "error")} prohibited this store from being saved:"
      %ul
        - @store.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :coords
    = f.text_field :coords
  .actions
    = f.submit 'Save'

app/views/stores/edit.html.haml
%h1 Editing store

= render 'form'

= link_to 'Show', @store
\|
= link_to 'Back', stores_path

app/views/stores/index.html.haml
%h1 Listing stores

/ :javascript
/ $(function() {
/   handler = Gmaps.build('Google');
/   handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
/     markers = handler.addMarkers([
/       {
/         "lat": 0,
/         "lng": 0,
/         "picture": {
/           "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
/           "width":  36,
/           "height": 36
/         },
/         "infowindow": "hello!"
/       }
/     ]);
/     handler.bounds.extendWith(markers);
/     handler.fitMapToBounds();
/   });
/   setTimeout(function(){handler.addMarkers(#{ @map_hash.to_json })},3000);
/   //markers = handler.addMarkers(#{ @map_hash.to_json });
/ })

/ %div(style='width: 800px')
/   #map(style='width: 800px; height: 400px;')

%table
  %tr
    %th Address
    %th Lon/Lat
    %th
    %th
    %th

  - @stores.each do |store|
    %tr
      %td= store.address
      %td= store.lon_lat
      %td= link_to 'Show', store
      %td= link_to 'Edit', edit_store_path(store)
      %td= link_to 'Destroy', store, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Store', new_store_path

app/views/stores/new.html.haml
%h1 New store

= render 'form'

= link_to 'Back', stores_path

app/views/stores/show.html.haml
%p#notice= notice

%p
  %b Address:
  = @store.address
%p
  %b Coords:
  = @store.coords

= link_to 'Edit', edit_store_path(@store)
\|
= link_to 'Back', stores_path