config/routes.rb
EsShopPractice::Application.routes.draw do

  devise_for :users

  resources :stores

  resources :laptops

  resources :televisions

  resources :cameras

  resources :reviews

  resources :products

  root to: "products#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_facet_row.html.haml
- checked = params[type][name][value] == "true" rescue false
- param = {type => {name => {value => !checked}}}
%li
  = link_to params.deep_merge(param) do
    - if checked
      = image_tag "checkbox_selected_enabled.jpg"
    - else
      = image_tag "checkbox_unselected_enabled.jpg"
    %span= label

app/views/application/_facets.html.haml
- @facets.each do |name, details|
  %h3= name
  %ul
    - case type = details["_type"]

      - when "terms"
        - details["terms"].each do |row|
          - label = "#{row['term']} (#{row['count']})"
          - value = row['term']
          = render partial: "facet_row", locals: {type: type, label: label, name: name, value: value}

      - when "range"
        - details["ranges"].each do |row|
          - from = row["from"]
          - to   = row["to"]
          - from_str  = "from #{from.to_i}" if from
          - to_str    = "to #{to.to_i}"      if to
          - count_str = "(#{row['count']})"
          - value = [from_str, to_str].compact.join("_").gsub(" ", "_")
          - label = [from_str, to_str, count_str].compact.join(" ")
          = render partial: "facet_row", locals: {type: type, label: label, name: name, value: value}

app/views/application/_navbar.html.haml
.navbar.navbar-default
  .navbar-brand.strong= link_to "ElasticSearch Store", root_path
  %ul.nav.navbar-nav.navbar-left
    %li= link_to "Products", products_path
    %li= link_to "Stores", stores_path
  %form.navbar-form.navbar-left
    .form-group
      %input.form-control{placeholder: "Search", type: "text", value: params[:q], :name => "q"}/
    %button.btn.btn-default{type: "submit"} Submit
  .nav.navbar-nav.navbar-right
    - if user_signed_in?
      %li.navbar-text Logged in as #{current_user.name}
      %li= link_to 'Edit Profile', edit_user_registration_path
      %li= link_to 'Logout',  destroy_user_session_path, method: :delete
    - else
      %li= link_to 'Sign up', new_user_registration_path
      %li= link_to 'Login', new_user_session_path

app/views/application/index.html.haml
.row
  .col-md-2= render "facets"
  .col-md-10
    %h1 Listing products

    %table
      %tr
        %th Name
        %th Description
        %th Manufacturer
        %th Price
        %th
        %th
        %th

      - @products.each do |product|
        %tr
          %td= product.name
          %td= product.description
          %td= product.manufacturer
          %td= product.price
          %td= link_to 'Show', product
          %td= link_to 'Edit', edit_product_path(product)
          %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Product', new_product_path